--Увеличиваем размер колонок в истории
ALTER TABLE act_hi_varinst ALTER COLUMN text_ TYPE CHARACTER VARYING(10000);
ALTER TABLE act_hi_varinst ALTER COLUMN text2_ TYPE CHARACTER VARYING(10000);
ALTER TABLE act_ru_variable ALTER COLUMN text_ TYPE CHARACTER VARYING(10000);
ALTER TABLE act_ru_variable ALTER COLUMN text2_ TYPE CHARACTER VARYING(10000);