INSERT INTO clients(id, surname, firstname, middlename, birth_date, gender, birth_place,
                    resident, resident_rf, tax_residence, tax_payer_number, public_official_status,
                    foreign_public_official_type, russian_public_official_type, relations,
                    public_official_position, public_official_name_and_position,
                    beneficial_owner, business_relations, activities_goal, business_relations_goal,
                    risk_level_desc, business_reputation, financial_stability, finances_source,
                    personal_data_consent, inn, snils, license_driver, sign_ipdl,
                    sign_pdl, adoption_pdl_written_decision, has_fatca, has_beneficial_owner,
                    has_beneficiary, bankruptcy_info, bankruptcy_stage, risk_level,
                    latin_name, code_word, status, email, agreements, nationalities,
                    registration_date, cache_save_time, last_update_date)
VALUES (10, 'Иванов', 'Иван', 'Петрович', TIMESTAMP '1986-03-30', 'MALE', 'СССР',
        'russian', true, 'FOREIGN', '1234567891234', 'NONE',
        null, null, null,
        'Директор', 'Иванов Иван Петрович, Клиент',
        null, null, null, null,
        'Низкий', null, 'STABLE', 'Бизнес',
        true, '1234567891234', '12345678910', null, false,
        false, false, false, false,
        false, 'NOT_BANKRUPT', '', 'NORMAL',
        'IVANOV IVAN PETROVICH', 'someword', 'STATUS-OK', 'ivanov@example.org', null, null,
        TIMESTAMP '2018-01-01', CURRENT_DATE, TIMESTAMP '2018-01-01');
