/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.services.insurance.controllers;

import ru.softlab.efr.services.insurance.model.rest.AcquiringProgramData;
import ru.softlab.efr.services.insurance.model.rest.ErrorModel;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the AcquiringProgram API
 */
public interface AcquiringProgramApi {

    /**
     * Создать программу для покупки в ЛК 
     * @param request Данные для создания программы для покупки в ЛК  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v2/dict/acquiring/program",
        method = RequestMethod.POST)
    ResponseEntity<AcquiringProgramData> createProgram(@Valid @RequestBody AcquiringProgramData request) throws Exception;



    /**
     * Получить программу для покупки в ЛК по идентификатору 
     * @param id Идентификатор программы  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v2/dict/acquiring/program/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<AcquiringProgramData> getProgram(@PathVariable("id") Long id) throws Exception;



    /**
     * Получить список программ для покупки в ЛК   
     * @param pageable параметры пагинации 
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v2/dict/acquiring/program",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Page<AcquiringProgramData>> getProgramList(@PageableDefault(value = 50) Pageable pageable) throws Exception;



    /**
     * Обновить программу для покупки в ЛК 
     * @param id Идентификатор программы для покупки в ЛК
     * @param request Данные для создания программы для покупки в ЛК  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v2/dict/acquiring/program/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<AcquiringProgramData> updateProgram(@PathVariable("id") Long id,@Valid @RequestBody AcquiringProgramData request) throws Exception;


}
