/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.services.insurance.controllers;

import ru.softlab.efr.services.insurance.model.rest.AvailProgramKindData;
import ru.softlab.efr.services.insurance.model.rest.AvailProgramKindListRs;
import ru.softlab.efr.services.insurance.model.rest.CreateAvailProgramKindResponse;
import ru.softlab.efr.services.insurance.model.rest.ErrorModel;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the AvailProgramKind API
 */
public interface AvailProgramKindApi {

    /**
     * Создать запись в справочнике доступности видов программ страхования. 
     * @param createAvailProgramKindRq Запрос создания записи в справочнике доступности видов программ страховаия.  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/availprogramkind/dict",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CreateAvailProgramKindResponse> createAvailProgramKind(@Valid @RequestBody AvailProgramKindData createAvailProgramKindRq) throws Exception;



    /**
     * Удалить сущность доступности вида программы страхования. 
     * @param id Идентификатор сущности доступности вида программы страхования.  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/availprogramkind/dict/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteAvailProgramKind(@PathVariable("id") Long id) throws Exception;



    /**
     * Получить сущность доступности вида программы страхования по ID. 
     * @param id Идентификатор сущности доступности вида программы страхования.  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/availprogramkind/dict/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<AvailProgramKindData> getAvailProgramKindById(@PathVariable("id") Long id) throws Exception;



    /**
     * Получить список программ страхования   
     * @param pageable параметры пагинации 
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/availprogramkind/dict",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Page<AvailProgramKindData>> getAvailProgramKindDictList(@PageableDefault(value = 50) Pageable pageable) throws Exception;



    /**
     * Получить список доступных видов программ страхования   
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/availprogramkind",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<AvailProgramKindListRs> getAvailProgramKinds() throws Exception;



    /**
     * Обновить сущность доступности вида программы страхования. 
     * @param id Идентификатор сущности доступности вида программы страхования.
     * @param updateProgramRequest Запрос обновления сущности доступности вида программы страхования.  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/availprogramkind/dict/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateAvailProgramKind(@PathVariable("id") Long id,@Valid @RequestBody AvailProgramKindData updateProgramRequest) throws Exception;


}
