/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.services.insurance.controllers;

import ru.softlab.efr.services.insurance.model.client.ErrorModel;
import ru.softlab.efr.services.insurance.model.client.ListClientsResponse;
import java.time.LocalDate;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the PrivateClientsData API
 */
public interface PrivateClientsDataApi {

    /**
     * Список клиентов 
     * @param surName Фамилия клиента
     * @param firstName Имя клиента
     * @param middleName Отчество клиента
     * @param birthDate Дата рождения
     * @param phoneNumber Номер телефона  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v2/private/clients/search",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ListClientsResponse> clientsSearchWithOutPermissions( @Valid @RequestParam(value = "surName", required = false) String surName, @Valid @RequestParam(value = "firstName", required = false) String firstName, @Valid @RequestParam(value = "middleName", required = false) String middleName, @Valid @RequestParam(value = "birthDate", required = false) LocalDate birthDate, @Valid @RequestParam(value = "phoneNumber", required = false) String phoneNumber) throws Exception;


}
