/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.services.insurance.controllers;

import ru.softlab.efr.services.insurance.model.rest.ErrorModel;
import ru.softlab.efr.services.insurance.model.rest.RedemptionData;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the Redemption API
 */
public interface RedemptionApi {

    /**
     * Создать запись в справочнике выкупных коэффициентов. 
     * @param updateRedemptionRq Запрос создания записи в справочнике выкупных коэффициентов.  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/dict/redemption",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<RedemptionData> createRedemption(@Valid @RequestBody RedemptionData updateRedemptionRq) throws Exception;



    /**
     * Удалить запись справочника выкупных коэффициентов 
     * @param id Идентификатор записи в справочнике выкупных коэффициентов.  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/dict/redemption/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteRedemption(@PathVariable("id") Long id) throws Exception;



    /**
     * Получить запись из справочника выкупных коэффициентов. 
     * @param id Идентификатор записи в справочнике выкупных коэффициентов.  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/dict/redemption/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<RedemptionData> getRedemption(@PathVariable("id") Long id) throws Exception;



    /**
     * Получить список справочника выкупных коэффициентов.   
     * @param pageable параметры пагинации 
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/dict/redemption",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Page<RedemptionData>> getRedemptionList(@PageableDefault(value = 50) Pageable pageable) throws Exception;



    /**
     * Обновить запись в справочнике выкупных коэффициентов. 
     * @param id Идентификатор записи в справочнике выкупных коэффициентов.
     * @param updateRedemptionRq Запрос обновления записи выкупных коэффициентов.  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/insurance-service/v1/dict/redemption/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<RedemptionData> putRedemption(@PathVariable("id") Long id,@Valid @RequestBody RedemptionData updateRedemptionRq) throws Exception;


}
